apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: traefik-ingress
  namespace: security-goals
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: app
              servicePort: 3000
          - path: /security-goals
            backend:
              serviceName: api
              servicePort: 3000
          - path: /runner
            backend:
              serviceName: runner
              servicePort: 3000
