apiVersion: v1
kind: Service
metadata:
  name: nfs
  labels:
    app: nfs
  namespace: security-goals
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs