apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
  labels:
    app: nfs
  namespace: security-goals
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs
  template:
    metadata:
      labels:
        role: nfs
    spec:
      containers:
      - name: nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: checks
      volumes:
        - name: checks
          gcePersistentDisk:
            pdName: checks
            fsType: ext4