apiVersion: batch/v1
kind: Job
metadata:
  name: cm-8
  namespace: security-goals
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: "gcr.io/security-goals/checks/url-exists"
          imagePullPolicy: Always
          name: "cm-8"
          env:
            - name: ORIGIN
              value: "gcr.io/security-goals/checks/url-exists"
            - name: COMPONENT
              value: "Source code"
            - name: DESCRIPTION
              value: "The application uses a packages.json to manage the information inventory in source control with a log of changes by users."
            - name: SATISFIES
              value: "CM-8"
            - name: URL
              value: "https://github.com/cds-snc/cra-alpha/blob/master/package.json"
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim