apiVersion: batch/v1
kind: Job
metadata:
  name: sc-8
  namespace: security-goals
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'gcr.io/security-goals/checks/https-scan:latest'
          imagePullPolicy: Always
          name: sc-8
          env:
            - name: ORIGIN
              value: 'gcr.io/security-goals/checks/https-scan:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'This application follows the ITPIN guidelines'
            - name: SATISFIES
              value: 'sc-8'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
