apiVersion: batch/v1
kind: Job
metadata:
  name: si-10
  namespace: security-goals
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: "gcr.io/security-goals/checks/url-exists"
          imagePullPolicy: Always
          name: "si-10"
          env:
            - name: ORIGIN
              value: "gcr.io/security-goals/checks/url-exists"
            - name: COMPONENT
              value: "Source code"
            - name: DESCRIPTION
              value: "The application defines an API schema to validate inputs against."
            - name: SATISFIES
              value: "SI-10"
            - name: URL
              value: "https://github.com/cds-snc/cra-alpha/blob/master/src/utils.js"
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim